"""Office operations executed inside an ACA Sandbox.

The gateway uploads this module to the Sandbox and invokes it with a JSON
request file. User input never becomes part of a shell command.
"""

from __future__ import annotations

import importlib.util
import json
import shutil
import subprocess
import sys
import tempfile
import uuid
from pathlib import Path


class RunnerError(RuntimeError):
    def __init__(
        self,
        status: int,
        message: str,
        details: dict[str, object] | None = None,
    ) -> None:
        super().__init__(message)
        self.status = status
        self.message = message
        self.details = details or {}


def load_reference():
    spec = importlib.util.spec_from_file_location(
        "office_reference_server",
        "/app/server.py",
    )
    if spec is None or spec.loader is None:
        raise RunnerError(500, "Office reference module could not be loaded")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def resolve_job(reference, payload: dict[str, object]) -> Path:
    job_id = payload.get("jobId")
    if (
        not isinstance(job_id, str)
        or not job_id.isalnum()
        or len(job_id) > 64
    ):
        raise RunnerError(400, "Invalid jobId")
    job_dir = reference.BASE_DIR / job_id
    if not job_dir.is_dir():
        raise RunnerError(404, "Job not found")
    return job_dir


def generate(reference, payload: dict[str, object]) -> dict[str, object]:
    title = payload.get("title")
    content = payload.get("content")
    if not isinstance(title, str) or not title.strip():
        raise RunnerError(400, "title is required")
    if not isinstance(content, str) or not content.strip():
        raise RunnerError(400, "content is required")
    if len(title) > reference.MAX_TITLE_CHARS:
        raise RunnerError(
            400,
            f"title must be at most {reference.MAX_TITLE_CHARS} characters",
        )
    if len(content) > reference.MAX_CONTENT_CHARS:
        raise RunnerError(
            400,
            f"content must be at most {reference.MAX_CONTENT_CHARS} characters",
        )
    if reference.ILLEGAL_XML_CONTROL.search(
        title
    ) or reference.ILLEGAL_XML_CONTROL.search(content):
        raise RunnerError(
            400,
            "title or content contains unsupported control characters",
        )

    reference.BASE_DIR.mkdir(parents=True, exist_ok=True)
    job_id = uuid.uuid4().hex
    job_dir = reference.BASE_DIR / job_id
    job_dir.mkdir()
    docx_path = job_dir / "report.docx"
    pdf_path = job_dir / "report.pdf"
    pptx_path = job_dir / "report.pptx"
    xlsx_path = job_dir / "report.xlsx"

    try:
        document = reference.Document()
        document.add_heading(title.strip(), level=0)
        for line in content.strip().splitlines():
            document.add_paragraph(line)
        document.save(docx_path)

        workbook = reference.Workbook()
        worksheet = workbook.active
        worksheet.title = "Report"
        worksheet["A1"] = reference.spreadsheet_literal(title.strip())
        worksheet["A2"] = "Generated by AI Workspace Office Sandbox"
        row_index = 4
        for line in content.strip().splitlines():
            chunks = [
                line[start : start + reference.EXCEL_CELL_MAX_CHARS]
                for start in range(
                    0,
                    len(line),
                    reference.EXCEL_CELL_MAX_CHARS,
                )
            ] or [""]
            for chunk in chunks:
                worksheet.cell(
                    row=row_index,
                    column=1,
                    value=reference.spreadsheet_literal(chunk),
                )
                row_index += 1
        worksheet.column_dimensions["A"].width = 80
        workbook.save(xlsx_path)

        presentation = reference.Presentation()
        title_slide = presentation.slides.add_slide(
            presentation.slide_layouts[0]
        )
        title_slide.shapes.title.text = title.strip()
        title_slide.placeholders[1].text = (
            "Generated by AI Workspace Office Sandbox"
        )
        content_slide = presentation.slides.add_slide(
            presentation.slide_layouts[1]
        )
        content_slide.shapes.title.text = "Summary"
        text_frame = content_slide.placeholders[1].text_frame
        text_frame.clear()
        for index, line in enumerate(content.strip().splitlines()):
            paragraph = (
                text_frame.paragraphs[0]
                if index == 0
                else text_frame.add_paragraph()
            )
            paragraph.text = line
        presentation.save(pptx_path)

        subprocess.run(
            [
                "libreoffice",
                f"-env:UserInstallation=file:///tmp/lo-profile-{job_id}",
                "--headless",
                "--convert-to",
                "pdf",
                "--outdir",
                str(job_dir),
                str(docx_path),
            ],
            check=True,
            capture_output=True,
            text=True,
            timeout=120,
        )
    except subprocess.TimeoutExpired as error:
        shutil.rmtree(job_dir, ignore_errors=True)
        raise RunnerError(504, "Document conversion timed out") from error
    except subprocess.CalledProcessError as error:
        shutil.rmtree(job_dir, ignore_errors=True)
        raise RunnerError(
            500,
            "Document conversion failed",
            {"stderr": (error.stderr or "")[-2000:]},
        ) from error
    except (OSError, ValueError, KeyError) as error:
        shutil.rmtree(job_dir, ignore_errors=True)
        raise RunnerError(500, "Document generation failed") from error

    paths = (docx_path, pdf_path, pptx_path, xlsx_path)
    if not all(path.is_file() for path in paths):
        shutil.rmtree(job_dir, ignore_errors=True)
        raise RunnerError(500, "Expected document artifacts were not generated")
    return {
        "jobId": job_id,
        "files": [
            reference.file_metadata(path, job_id) for path in paths
        ],
    }


def convert(reference, payload: dict[str, object]) -> dict[str, object]:
    job_dir = resolve_job(reference, payload)
    source = payload.get("source")
    target = payload.get("target")
    if not isinstance(source, str) or not isinstance(target, str):
        raise RunnerError(400, "source and target are required strings")
    output_name = reference.CONVERSION_MATRIX.get((source, target))
    if output_name is None:
        raise RunnerError(
            400,
            "Conversion is not allowed",
            {
                "allowed": [
                    {"source": allowed_source, "target": allowed_target}
                    for allowed_source, allowed_target in sorted(
                        reference.CONVERSION_MATRIX
                    )
                ]
            },
        )
    source_path = job_dir / source
    if not source_path.is_file():
        raise RunnerError(404, f"{source} not found")

    job_id = job_dir.name
    output_path = job_dir / output_name
    with tempfile.TemporaryDirectory(
        prefix=f"convert-{job_id}-",
        dir=job_dir,
    ) as temporary:
        temporary_dir = Path(temporary)
        produced = temporary_dir / f"{source_path.stem}.{target}"
        try:
            subprocess.run(
                [
                    "libreoffice",
                    f"-env:UserInstallation=file:///tmp/lo-profile-{job_id}",
                    "--headless",
                    "--convert-to",
                    target,
                    "--outdir",
                    str(temporary_dir),
                    str(source_path),
                ],
                check=True,
                capture_output=True,
                text=True,
                timeout=120,
            )
        except subprocess.TimeoutExpired as error:
            raise RunnerError(504, "Conversion timed out") from error
        except subprocess.CalledProcessError as error:
            raise RunnerError(
                500,
                "Conversion failed",
                {"stderr": (error.stderr or "")[-2000:]},
            ) from error
        if not produced.is_file():
            raise RunnerError(500, "Converted artifact was not produced")
        shutil.copyfile(produced, output_path)
    return {
        "jobId": job_id,
        "source": source,
        "target": target,
        "files": [reference.file_metadata(output_path, job_id)],
    }


def edit(reference, payload: dict[str, object]) -> dict[str, object]:
    job_dir = resolve_job(reference, payload)
    operations = payload.get("operations")
    if not isinstance(operations, list) or not operations:
        raise RunnerError(400, "operations must be a non-empty array")
    if len(operations) > reference.MAX_EDIT_OPERATIONS:
        raise RunnerError(
            400,
            f"operations must be at most {reference.MAX_EDIT_OPERATIONS}",
        )
    for operation in operations:
        if not isinstance(operation, dict):
            raise RunnerError(400, "each operation must be an object")
        if operation.get("op") not in reference.ALLOWED_EDIT_OPERATIONS:
            raise RunnerError(
                400,
                f"Unsupported operation: {operation.get('op')}",
                {"allowed": sorted(reference.ALLOWED_EDIT_OPERATIONS)},
            )
    try:
        outputs = reference.apply_edit_operations(job_dir, operations)
    except (
        reference.EditError,
        reference.IllegalCharacterError,
        ValueError,
    ) as error:
        raise RunnerError(400, str(error)) from error
    except OSError as error:
        raise RunnerError(
            500,
            "Edit failed due to a filesystem error",
        ) from error
    return {
        "jobId": job_dir.name,
        "applied": len(operations),
        "files": [
            reference.file_metadata(path, job_dir.name) for path in outputs
        ],
    }


def main() -> None:
    if len(sys.argv) != 3:
        raise RunnerError(400, "action and request path are required")
    action = sys.argv[1]
    request_path = Path(sys.argv[2])
    payload = json.loads(request_path.read_text(encoding="utf-8"))
    if not isinstance(payload, dict):
        raise RunnerError(400, "request must be a JSON object")
    reference = load_reference()
    handlers = {
        "generate": generate,
        "convert": convert,
        "edit": edit,
    }
    handler = handlers.get(action)
    if handler is None:
        raise RunnerError(400, f"Unsupported action: {action}")
    print(json.dumps(handler(reference, payload), ensure_ascii=False))


if __name__ == "__main__":
    try:
        main()
    except RunnerError as error:
        print(
            json.dumps(
                {
                    "status": error.status,
                    "error": error.message,
                    **error.details,
                },
                ensure_ascii=False,
            )
        )
        raise SystemExit(2)
    except Exception:
        print(json.dumps({"status": 500, "error": "Office operation failed"}))
        raise
